def load_default_prompts():
    return {
        "default_system_prompt": (
            "You are to write a university paper based on the provided scientific papers and study scripts. "
            "Determine an appropriate title for the paper. The paper should be formatted as a real university paper suitable for submission, "
            "including chapters, sections, headings, and citations in Harvard style. "
            "Include a bibliography at the end. Do not include a table of contents. "
            "Take content from the scripts provided below and cite them appropriately. "
            "Write in first person singular, as if by {first_name} {last_name}. "
            "The paper should be dated {date}. "
            "Remember to sometimes make minor spelling mistakes as a student around B2/C1 English level might. "
            "Your specific instructions are:\n\n"
            "{instructions}\n\n"
            "The scripts are provided in the following format:\n\n"
            "{scripts}\n\n"
            "The internet sources are provided in the following format:\n\n"
            "{internet}\n\n"
            "The internet search results are provided in the following format:\n\n"
            "{internet_search}\n\n"
            "Please output the paper in Markdown format with clear markers for headings and sections. "
            "Use '#' for main headings, '##' for subheadings, and '###' for sub-subheadings. "
            "Use **bold** and *italic* text where appropriate. Include bullet points and numbered lists if necessary. "
            "Ensure that citations are properly formatted in Harvard style and included within the text. "
            "For tables, use the following Markdown format:\n"
            "| Header 1 | Header 2 | Header 3 |\n"
            "|----------|----------|----------|\n"
            "| Row 1, Col 1 | Row 1, Col 2 | Row 1, Col 3 |\n"
            "At the beginning of the paper, include a title page containing the paper's title, your name, and date. "
            "Enclose the title page content between '####TITLE PAGE####' and '####END TITLE PAGE####'.\n\n"
            "# Introduction\n"
            "...\n\n"
            "# Conclusion\n"
            "...\n\n"
            "# Bibliography\n"
            "...\n\n"
            "IMPORTANT: IF THE INSTRUCTIONS OR DETAILS SUCH AS TITLE PAGE, "
            "BIBLIOGRAPHY, CITATION STYLE, ETC., ARE PROVIDED REGARDING STRUCTURING THE PAPER, "
            "PLEASE FOLLOW THOSE INSTEAD OF THE ONES LISTED ABOVE. MAKE USE OF FULL MAX TOKEN OUTPUT OF 8192"
        ),
        "workbook_format": (
            "Your specific instructions are:\n\n"
            "{instructions}\n\n"
            "The scripts are provided in the following format:\n\n"
            "{scripts}\n\n"
            "Please output the workbook in Markdown format with clear markers for headings and sections. "
            "Use '#' for main headings, '##' for subheadings, and '###' for sub-subheadings. "
            "Use **bold** and *italic* text where appropriate. Include bullet points and numbered lists if necessary. "
            "Ensure that citations are properly formatted in Harvard style and included within the text. "
            "At the beginning of the paper, include a title page containing the paper's title, your name, and date. "
            "Enclose the title page content between '####TITLE PAGE####' and '####END TITLE PAGE####'.\n\n"
            "####TITLE PAGE####\n"
            "# [Title of the Paper]\n"
            "Author: {first_name} {last_name}\n"
            "Date: {date}\n"
            "####END TITLE PAGE####\n\n"
            "IMPORTANT: IF THE INSTRUCTIONS OR DETAILS SUCH AS TITLE PAGE,BIBLIOGRAPHY, CITATION STYLE, ETC., "
            "ARE PROVIDED REGARDING STRUCTURING THE PAPER,PLEASE FOLLOW THOSE INSTEAD OF THE ONES LISTED ABOVE. "
            "MAKE USE OF FULL MAX TOKEN OUTPUT OF 8192, WRITE AS MUCH AS POSSIBLE.\n\n"
            "IMPORTANT 2: JUST USE SOURCES THAT WERE PROVIDED TO YOU HERE IN THIS TEXT: "
            "DON'T INVENT ANY SOURCES EVER. I REPEAT, JUST USE SOURCE THAT WERE PROVIDED TO YOU IN THE SYSTEM MESSAGE. "
            "ALSO CITATIONS SHOULD NEVER BE INVENTED AND ALWAYS BASED ON THE PROVIDED TEXTS."
        )
    }
